#!/usr/bin/env bash

# we need to set the permissions here because docker currently
# mounts volumes as root

chown -R couchdb:couchdb /usr/local/var/lib/couchdb \
  /usr/local/var/log/couchdb \
  /usr/local/var/run/couchdb \
  /usr/local/etc/couchdb

chmod -R 0770 /usr/local/var/lib/couchdb \
  /usr/local/var/log/couchdb \
  /usr/local/var/run/couchdb \
  /usr/local/etc/couchdb

chmod 664 /usr/local/etc/couchdb/*.ini
chmod 775 /usr/local/etc/couchdb/*.d

# Set up the proxy for couch lucene
sed -e 's/^;_google = {couch_httpd_proxy, handle_proxy_req, <<"http:\/\/www.google.com">>}$/_fti = {couch_httpd_proxy, handle_proxy_req, <<"http:\/\/localhost:5985">>}/' -i /usr/local/etc/couchdb/local.ini

# Start lucene
su - couchdb -c 'mon /opt/couchdb-lucene-0.9.0/bin/run' &

# Start couchdb
su - couchdb -c 'mon couchdb'

